/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e4e2dd",
        "surface-container-low": "#f5f3ed",
        "on-background": "#1b1c18",
        "on-secondary-fixed-variant": "#005049",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f3f1eb",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "background": "#F7F5EF",
        "primary-container": "#1c1b1b",
        "surface-container-high": "#eae8e2",
        "tertiary": "#000000",
        "on-secondary-fixed": "#00201d",
        "surface-bright": "#fbf9f3",
        "primary-fixed": "#e5e2e1",
        "on-tertiary-container": "#e55235",
        "surface-dim": "#dcdad4",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#1c1b1b",
        "secondary-fixed": "#62f9e7",
        "on-error-container": "#93000a",
        "secondary-container": "#62f9e7",
        "tertiary-fixed-dim": "#ffb4a4",
        "on-tertiary-fixed": "#3e0500",
        "secondary": "#006a61",
        "surface-variant": "#e4e2dd",
        "secondary-fixed-dim": "#3cdccb",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#474646",
        "tertiary-container": "#3e0500",
        "surface-tint": "#5f5e5e",
        "outline-variant": "#c4c7c7",
        "surface": "#F7F5EF",
        "on-tertiary-fixed-variant": "#8d1600",
        "outline": "#747878",
        "on-error": "#ffffff",
        "on-surface-variant": "#444748",
        "inverse-primary": "#c8c6c5",
        "on-tertiary": "#ffffff",
        "surface-container": "#f0eee8",
        "tertiary-fixed": "#ffdad3",
        "inverse-surface": "#30312d",
        "on-primary-container": "#858383",
        "on-secondary-container": "#007167",
        "on-surface": "#1b1c18",
        "on-primary": "#ffffff",
        "primary": "#151515",
        "aqua": "#32D6C5",
        "vermilion": "#F05A3C",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-mobile": "1.25rem",
        "unit-4xl": "6rem",
        "unit-xs": "0.25rem",
        "unit-xl": "2rem",
        "margin-mobile": "1.25rem",
        "max-width": "80rem",
        "gutter-desktop": "2rem",
        "unit-md": "1rem",
        "unit-3xl": "4rem",
        "unit-sm": "0.5rem",
        "margin-desktop": "3rem",
        "unit-2xl": "2.75rem",
        "unit-2xs": "0.125rem",
        "unit-lg": "1.5rem",
      },
      fontFamily: {
        sans: ["'Hanken Grotesk'", "system-ui", "sans-serif"],
        serif: ["'Newsreader'", "Georgia", "serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        "body-sm": ["'Hanken Grotesk'", "sans-serif"],
        "body-md": ["'Hanken Grotesk'", "sans-serif"],
        "body-lg": ["'Hanken Grotesk'", "sans-serif"],
        "label-mono": ["'JetBrains Mono'", "monospace"],
        "headline-sm": ["'Hanken Grotesk'", "sans-serif"],
        "headline-lg": ["'Newsreader'", "Georgia", "serif"],
        "headline-md": ["'Hanken Grotesk'", "sans-serif"],
        "headline-lg-mobile": ["'Newsreader'", "Georgia", "serif"],
        "code-block": ["'JetBrains Mono'", "monospace"],
        "display-xl": ["'Newsreader'", "Georgia", "serif"],
        "display-xl-mobile": ["'Newsreader'", "Georgia", "serif"],
        "label-caps": ["'Hanken Grotesk'", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["0.875rem", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-lg": ["1.125rem", { lineHeight: "1.65", letterSpacing: "0", fontWeight: "400" }],
        "label-mono": ["0.75rem", { lineHeight: "1.35", letterSpacing: "0.06em", fontWeight: "500" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.35", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["2.75rem", { lineHeight: "1.15", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-md": ["1.625rem", { lineHeight: "1.25", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["2rem", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "400" }],
        "code-block": ["0.875rem", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "display-xl": ["4.25rem", { lineHeight: "1.05", letterSpacing: "-0.03em", fontWeight: "400" }],
        "display-xl-mobile": ["2.5rem", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "label-caps": ["0.6875rem", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
